-------------------------------------------------------------------------
-- Design unit: R8 microcontroller simutation test bench
-- Description: R8 processor connected to a RAM memory
--      The RAM memory is able to load image files generated by the R8 simulator             
-------------------------------------------------------------------------

library IEEE;
use IEEE.std_logic_1164.all;   

entity R8_uC_tb is
end R8_uC_tb;								 
																					 
architecture behavioral of R8_uC_tb is
    
	signal clk 			: std_logic := '0';  	
	signal rst			: std_logic := '0';
	signal portA_io		: std_logic_vector(15 downto 0);   
														  							  	
begin
	
	-- Simulation time of first teste: 7200 ns
	
	 -- Generates the clock signal            
    clk <= not clk after 10 ns;	   			-- 100 MHz
    
    -- Generates the reset signal
    rst <='1', '0' after 5 ns;   
	
	-- It takes 5360 us to complete the simulation	
	
	portA_io <= "ZZZZZZZZZZZZZZZZ", "0010ZZZZZZZZZZZZ" after 80000 ns, "0000ZZZZZZZZZZZZ" after 360000 ns;
	
	--========================================================================================================
	-- R8 Microcontroller
	--========================================================================================================
    uC_R8: entity work.R8_uC
		generic map(																											
			IMAGE		=> "display_interface_BRAM.txt"											 
		)
        port map (
            clk     	=> clk,
        	rst     	=> rst,
        	portA_io	=> portA_io 
        );
		
	--========================================================================================================
	-- 7 Segments Display Interface will be conect direct to portA_io on R8_uc.vhd
	--========================================================================================================
 	
	
	
    
end behavioral;