-------------------------------------------------------------------------
-- Design unit: R8 simutation test bench
-- Description: R8 processor connected to a RAM memory
--      The RAM memory is able to load image files generated by the R8 simulator             
-------------------------------------------------------------------------

library IEEE;
use IEEE.std_logic_1164.all;   

entity R8_uC_tb is
end R8_uC_tb;

architecture behavioral of R8_uC_tb is
    
	signal clk 		: std_logic := '0';  	
	signal rst		: std_logic := '0';
	signal port_io	: std_logic_vector(15 downto 0);	
	
begin
    
    R8: entity work.R8_uC
		generic map(
			IMAGE		=> "rlt_simulation_BRAM.txt"
		)
        port map (
            clk     	=> clk,
        	rst     	=> rst,
        	port_io		=> port_io
        );
		
	port_io	<= 	"ZZZZZZZZZZZZZZZZ",
				"1010101010101010" after 3880 ns;
		
    -- Generates the clock signal            
    clk <= not clk after 10 ns;
    
    -- Generates the reset signal
    rst <='1', '0' after 5 ns;  
	
	-- Simulation time of first teste: 7200 ns
    
end behavioral;