-------------------------------------------------------------------------
-- Design unit: R8 simutation test bench
-- Description: R8 processor connected to a RAM memory
--      The RAM memory is able to load image files generated by the R8 simulator             
-------------------------------------------------------------------------

library IEEE;
use IEEE.std_logic_1164.all;   

entity R8_BRAM_tb is
end R8_BRAM_tb;

architecture behavioral of R8_BRAM_tb is
    
	signal clk : std_logic := '0';  	
	signal rst: std_logic := '0';
	signal segments: std_logic_vector(7 downto 0);
	signal display_en_n: std_logic_vector(3 downto 0);
    
begin
    
    R8: entity work.R8_BRAM
        port map (
            clk     		=> clk,
        	rst     		=> rst,
        	segments        => segments,
        	display_en_n    => display_en_n
        );
    
    -- Generates the clock signal            
    clk <= not clk after 10 ns;
    
    -- Generates the reset signal
    rst <='1', '0' after 5 ns;        
    
end behavioral;